POST http://127.0.0.1:3000/users/login
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkY2VhNDY2ZDYwOGFkOTUwNGZiZTIiLCJpYXQiOjE2NDgyMTc3NjR9.u8klqE-9ARxwmgolXl6ePLBwm50_SPdd2aby-nTAYQM

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###

GET http://127.0.0.1:3000/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkY2VhNDY2ZDYwOGFkOTUwNGZiZTIiLCJpYXQiOjE2NDgyMjAzNjR9.AEsIZgD6Es-ew-bfNHI77heD5d1b6bApWE_Q46YHXt4

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###

POST http://127.0.0.1:3000/users/signup
content-type: application/json

{
  "name": "Matt",
  "email": "matt@email.com",
  "password": "mattpassword"
}

###

POST http://127.0.0.1:3000/users/signup
content-type: application/json

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###

POST http://127.0.0.1:3000/users/signup
content-type: application/json


{
  "name": "Carl",
  "email": "carl@email.com",
  "password": "carlpassword"
}

###

POST http://127.0.0.1:3000/users/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkY2VhNDY2ZDYwOGFkOTUwNGZiZTIiLCJpYXQiOjE2NDgyMzIwNDJ9.m0aB4Q1erg5BjtpqmiRJnXHuIe6B573hP9C4xKlPVfM

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###

POST http://127.0.0.1:3000/users/logoutAll
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkY2VhNDY2ZDYwOGFkOTUwNGZiZTIiLCJpYXQiOjE2NDgyMzIxOTR9.SxtdZ2P8GWI77FeS50RTpLpPqDEjjV35sIyklDkyGmA

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###
DELETE http://127.0.0.1:3000/users/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNlMWFmZjY3NTIzNDNiMTdhZTJmN2IiLCJpYXQiOjE2NDgyMzczMTF9.5TJ8j6AfQMC4ezLgIXXZgvxmqi5j1saOsLuFi49tf1U

{
  "name": "George",
  "email": "george@email.com",
  "password": "georgepassword"
}

###
POST http://127.0.0.1:3000/shifts/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQwYTc5NGJjZWYzNTcyOGYzYTYyMzMiLCJpYXQiOjE2NDg0MDQzNzJ9.xD-uH0OUmagNJv_vmyhxJXSXB4LQZrw-qiQkJFtl9A8

{
  "where": "Poole",
  "billed": 185.50,
  "description": "Poole HighStreet",
  "owner": "6240a501221d86a8a9418708"
}